SELECT CHAR_LENGTH('SQL');

SELECT LOWER('SQL');

SELECT UPPER('sql');

SELECT LEFT('SQL',1);

SELECT SUBSTRING('PYTHON', 4, 2);

SELECT CONCAT('SQL', '-', 'Functions');

SELECT 'SQL' || '-' || 'Functions';

SELECT TRIM(' SQL FUNCTIONS ');

SELECT REPLACE('SQL', 'L', 'X');

SELECT REGEXP_REPLACE('SQL', '[A-Z]+', 'PYTHON');

-- NULL FUNCTIONS
SELECT NULLIF(NULL,NULL);

SELECT COALESCE(NULL,1,2);